---
:verbose: false
:concurrency: 10
:pidfile: tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:queues:
  - [critical, 2]
  - default
  - low

production:
  :concurrency: 25

staging:
  :concurrency: 15

:schedule:
  calculate_seller_monthly_commission:
    cron: '0 1 1 * *'   # Runs at 1:00 am 1st day of every month 
    class: CalculateSellerMonthlyCommissionWorker
